FROM ruby:2.7.1

RUN gem install bundler -v 2.1.4

WORKDIR /app

ENV BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"

# Start the main process.
CMD ["./bin/run.sh"]
