version: "3.6"

networks:
  es:
  backend:

volumes:
  bundle_cache:
  db-data:
  es-data:

services:
  elasticsearch:
    image: elasticsearch:8.2.0
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
    networks:
      - backend
      - es
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"

  kibana:
    image: kibana:8.2.0
    networks:
      - es
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"

  api:
    build:
      context: ./
      dockerfile: Dockerfile.local
    container_name: api
    environment:
      PORT: "3000"
    volumes:
      - .:/app
      - db-data:/app/db/test.sqlite3
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - elasticsearch
    networks:
      - backend
    tty: true
    stdin_open: true
